name: jads
channels:
  - defaults
  - conda-forge
  - damianavila82
dependencies:
  - bokeh
  - numpy
  - matplotlib
  - pandas
  - pip
  - pip:
    - dtreeviz
    - treebeard
    - jupyterlab
    - -e .
  - python >= 3.7
  - pyarrow
  - rise
  - seaborn
  - scikit-learn
  - spacy
  - toolz
